#General formods (FM) configuration across modules
FM: 
  #General code options for the modules
  code: 
    #theme:           "solarized_light"    
    theme:           "vibrant_ink"    
    showLineNumbers: TRUE
  ui:
    # See ?actionBttn for styles
    button_style: "fill"
    color_green:  "#00BB8A"
    color_red:    "#FF475E"
    color_blue:   "#0088FF"
    color_purple: "#bd2cf4"
  labels:
    default_ds:         "Original data set"
  user_files:
    use_tmpdir:     TRUE
  logging:
    enabled:        TRUE
    timestamp:      TRUE
    timestamp_fmt: "%Y-%m-%d %H:%M:%S"
    log_file:      "formods_log.txt"
    console:       TRUE
# Upload Data  (UD) configuration
UD:
  # Controls what is shown in the compact ui mode: UD_ui_compact
  compact:
    code:    TRUE 
    preview: TRUE 
  labels:
    upload_button: "Select file"
    tab_main:      "Upload File"
    tab_code:      "Code"
    tab_preview:   "Data Preview"
    # In the following you can use placeholder for the follwing:
    # ===EXT===        Uploaded file extension
    # ===FILE===       Loaded file name
    # ===ALLOWEDEXT=== Allowed file extensions
    msg_bad_extension: |- 
      Incorrect file extension (===EXT===). Unable to load file  ===FILE===.
      Only the following extesions are allowed: ===ALLOWEDEXT===.
  tooltips:
    show_code:         "Show data reading code"
  formatting:
    # Dimensions of the table preview in pixels
    preview:    
      width:  500
      height: 400
    code:
      width:  500
      height: 150
  # The app supports csv, tsv, xls and xlsx. You can remove those you don't
  # want to use
  allowed_extensions: 
    - csv
    - tsv
    - xls
    - xlsx
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
  # Name of the data set after being loaded
  ds_object_name: "myDS"
# Data Wrangling (DW) configuration
DW: 
  # Controls what is shown in the compact ui mode: DW_ui_compact
  compact:
    code:    TRUE 
    preview: TRUE 
  tooltips: 
    # Set to FALSE to disable tool tips for this module
    include: TRUE
    show_code:            "Show data wrangling code"
    dw_elements:          "Current wrangling elements"
  labels: 
    tab_main:             "Wrangle"
    tab_code:             "Code"
    add_element:          "Add Operation/Action"
    fds_filter_column:    "Filter by Column"
    fds_filter_operator:  "Condition"
    fds_filter_rhs:       "Matching"
    fds_mutate_column:    "Column to Mutate"
    fds_mutate_rhs:       "New Value"
    fds_rename_column:    "Curret Column"   
    fds_rename_rhs:       "New Name"
    fds_group_column:     "Columns to Group"
    new_dw:               "New"
    del_dw:               "Delete"
    copy_dw:              "Copy"
    save_dw:              "Save"
    no_dataset:           "No dataset loaded!"
    no_dw_elements:       "No data wrangling elements defined yet"
  errors:
    fds_filter_column:    "Filter column not specified."
    fds_filter_operator:  "Filter codition not specified."
    fds_filter_rhs:       "Filter RHS not specified."
    fds_mutate_column:    "Mutate column not specified."
    fds_mutate_rhs:       "Mutate RHS not specified."
    fds_rename_column:    "Column to rename not specified."   
    fds_rename_rhs:       "New column name not specified."
    fds_group_column:     "No columns to group specified."
    current_key:          "Short description"
    current_key_empty:    "The data view description field cannot be empty"
    unknown_action:       "The selection action is not supported."
    no_rows:              "There are no rows in the data set."
    element_not_added:    "Unable to add the data wrangling element:"
    fix_bad_element:      "There is a bad element in the data wrangling chain,\nyou need to fix that before adding new elements"
  operators:  
    # Do not change the type or rop. Only modify the text element
    - type: "factor"
      text: "is one of"
      rop:  "%in%"
    - type: "factor"
      text: "is not"
      rop:  "!%in%"
    - type: "not_factor"
      text: "is within the range"
      rop:  "within"
    - type: "not_factor"
      text: "is equal to"
      rop:  "=="
    - type: "not_factor"
      text: "is not equal to"
      rop:  "!="
  actions:
    filter:
      choice:  "Filter"   
      subtext: "Filter data"
    mutate:
      choice:  "Alter"  
      subtext: "Change the contents of a column"
    rename:
      choice:  "Rename"  
      subtext: "Rename column"
    group:  
      choice:  "Group"   
      subtext: "Group subsequent operations by columns"
    ungroup:
      choice:  "Ungroup" 
      subtext: "Removing groping"                        
  formatting:
    # dimensions of the table preview in pixels
    preview:    
      width:  1000
      height: 600
    # Dimensions of the table with the data wrangling elements
    dw_elements:    
      width:  600
      height: 200
    current_key:
      width: 300
    code:
      width:  500
      height: 200
    # Button sizes from actionBttn (shinyWidgets) 
    # xs,sm, md, lg.
    button_dw_del:
      size: "sm" 
      block: TRUE 
    button_dw_save:
      size: "sm" 
      block: TRUE 
    button_dw_copy:
      size: "sm" 
      block: TRUE 
    button_dw_new:
      size: "sm" 
      block: TRUE 
    button_dw_add_element:
      size: "sm" 
      block: TRUE 
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
  # Name of the data set after wrangling it should be different than the value
  # in the UD section
  ds_object_name: "DW_myDS"
# Figure Generation (FG) configuration
FG:
  # Controls what is shown in the compact ui mode: FG_ui_compact
  compact:
    code:    TRUE 
    preview: "ggplot"   # Either "ggplot" or "plotly"
  tooltips: 
    # Set to FALSE to disable tool tips for this module
    include: TRUE
    components:
      manual:
        x:             "Numeric location on the x-axis"
        "y":           "Numeric location on the y-axis"
        color:         "A named color red, blue, green"
        linetype:      "Specify either solid, dashed, dotted, dotdash, longdash or twodash"
        shape:         "Open shapes: square (0), circle (1), triangle (2); Filled shapes:  square (15), circle (16), triangle (17)"
        size:          "Numeric value"
        alpha:         "Numeric value between 0 (completely transparent) and 1 (solid)"
        group:         NULL
        xintercept:    NULL
        yintercept:    NULL
    caption:           "Optional figure caption that will be carried over and used in other elements (e.g. reporting)"
    fig_key:           "Unique descriptive figure key used for referencing figures."
    show_code:         "Show figure generation code"
    fg_elements:       "Current figure elements"
  labels:
    components:
      x:             "x-axis"
      "y":           "y-axis"
      color:         "color"
      linetype:      "line type"
      shape:         "shape"     
      size:          "size"     
      alpha:         "transparency"
      group:         "group"     
      xintercept:    "x intercept"
      yintercept:    "y intercept"
    ph:              
      xlab:          "x-axis label"
      ylab:          "y-axis label"
      ggtitle:       "plot title"
      caption:       "optional caption text here"
      fig_key:       "short description"
      manual:        "Manual"
    manual:          "Manual"
    not_used:        "Not Used"
    curr_figs_none:  "No figures yet created"
    no_fig_elements: "Add figure elements"
    new_fig:         "New"
    save_fig:        "Save"
    del_fig:         "Delete"
    copy_fig:        "Copy"
    upds_fig:        "Data set"
    add_ele:         "Add Figure Element"
    msg_bad_label:   "No labels were specified, unable to add element."
    msg_bad_facet:   "At least one column must be selected to add a faceting element."
    msg_bad_element: "Unable to add the specified element: ===ELEMENT==="
    msg_bad_manual_comp: |- 
      The plot element component ===COMP=== was specified manually but 
      no manual value was provided.
    select_current_fig:  "Current figure"
    select_current_view: "Data from"
    no_figures_defined:  "No figures have been defined"
  errors:
    element_not_added:    "Unable to add the data figure element:"
    current_key_empty:    "The figure description field cannot be empty."
    only_one_facet:       "This figure already has a faceting element."
  elements:
    # For each element below you should only modify the choice and subtext
    # elements
    line:
      choice:  "Line"     
      subtext: "Continuous line"
      ui_aes:  ["x", "y", "color", "group", "linetype", "size", "alpha"]
      aes_req: ["x", "y"]
      fcn:     "geom_line"
    point:
      choice:  "Point"  
      subtext: "Scatter plot"
      ui_aes:  ["x", "y", "color", "group", "shape", "size", "alpha",]
      aes_req: ["x", "y"]
      fcn:     "geom_point"
    hguide:
      choice:  "H-Guide"  
      subtext: "Horizontal guide"
      ui_aes:  ["yintercept", "linetype", "color", "size"]
      aes_req: ["yintercept"]
      fcn:     "geom_hline"
    vguide:
      choice:  "V-Guide"  
      subtext: "Vertical guide"
      ui_aes:  ["xintercept", "linetype", "color", "size"]
      aes_req: ["xintercept"]
      fcn:     "geom_vline"
    facet:
      choice:  "Facet"  
      subtext: "Facet by one or more variables"
    label:
      choice:  "Label"  
      subtext: "Label axes or plot title"
      ui_text: ["xlab", "ylab", "ggtitle"]
  formatting:
    # Dimensions of code snippet box
    code:
      width:  500
      height: 150
    # Dimensions of the figure preview
    # Must be numeric
    preview:    
      width:  1000
      height: 600
    #If you make the slider width = preview it will
    # span the bottom of the figure
    select_fg_page:    
      width:  1000
    # Dimensions of the caption text area
    caption:    
      width:  "300px"
      height: "75px"
    components:
      aes:
        width: "100px"
      facet:
        width: "200px"
      label:
        width: "150px"
    select_current_fig:
      width: 200
    select_current_view:
      width: 200
    # Dimensions of the table with the figure generation elements
    fg_elements:    
      width:  600
      height: 200
    # When faceting is selected (wrapping or grid) the result will be
    # paginated according to the dimensions below:
    faceting:  
      nrow:  3
      ncol:  4
    # Button sizes from actionBttn (shinyWidgets) 
    # xs,sm, md, lg.
    button_fig_del:
      size: "sm" 
      block: TRUE
    button_fig_save:
      size: "sm" 
      block: TRUE
    button_fig_copy:
      size: "sm" 
      block: TRUE
    button_fig_new:
      size: "sm" 
      block: TRUE
    button_fig_add:
      size: "sm" 
      block: TRUE
    button_fig_upds:
      size: "sm" 
      block: TRUE
  # You can put any post_processing you want to apply to all figures.
  # The ggplot object will be avialble as the ===FGOBJ=== 
  post_processing: |-
    ===FGOBJ=== = ===FGOBJ=== + theme_light()
  fg_object_name: "myp"
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
ASM:
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
  formatting:
    input_load_state:
      width: "100%"
    ui_asm_save_name:
      width: "100%"
    button_state_save:
      size: "sm" 
      block: TRUE
  labels:    
    ui_asm_save_name:    "Save Analysis"
    ui_asm_save_name_ph: "my_analysis"
    save_state:          "Save"
    input_load_state:    "Load Analysis"
    upload_button:       "Load"
    upload_placeholder:  "Select analysis file" 
  errors:
    bad_input: "Input error message"
  tooltips: 
    # Set to FALSE to disable tool tips for this module
    include: TRUE
    components:
      input_tip: "My tool tip"
# The ZZ field is a skeleton for constructing new modules
ZZ:
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
  # put different formatting options (widths, heights, 
  # shinyWidgets button sizes, etc) here.
  formatting:
    input:
      width: 100
  labels:    
    input_label: "This is the text for a label"
  errors:
    bad_input: "Input error message"
  tooltips: 
    # Set to FALSE to disable tool tips for this module
    include: TRUE
    components:
      input_tip: "My tool tip"
