#General formods (FM) configuration across modules
FM: 
  #General code options for the modules
  code: 
    theme:           "solarized_light"    
    showLineNumbers: TRUE
# Upload Data  (UD) configuration
UD:
  # Controls what is shown in the compact ui mode: UD_ui_compact
  compact:
    code:    TRUE 
    preview: TRUE 
  labels:
    upload_button: "Select file"
    tab_main:      "Upload File"
    tab_code:      "Code"
    tab_preview:   "Data Preview"
    # In the following you can use placeholder for the follwing:
    # ===EXT===        Uploaded file extension
    # ===FILE===       Loaded file name
    # ===ALLOWEDEXT=== Allowed file extensions
    msg_bad_extension: |- 
      Incorrect file extension (===EXT===). Unable to load file  ===FILE===.
      Only the following extesions are allowed: ===ALLOWEDEXT===.
  # Dimensions of the table preview in pixels
  preview:    
    width:  400
    height: 400
  # Dimensions of the table with the data wrangling elements
  dw_elements:    
    width:  400
    height: 400
  # The app supports csv, tsv, xls and xlsx. You can remove those you don't
  # want to use
  allowed_extensions: 
    - csv
    - tsv
    - xls
    - xlsx
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
# Data Wrangling (DW) configuration
DW: 
  # Controls what is shown in the compact ui mode: DW_ui_compact
  compact:
    code:    TRUE 
    preview: TRUE 
  labels: 
    tab_main:             "Wrangle"
    tab_code:             "Code"
    add_element:          "Add Operation/Action"
    fds_filter_column:    "Filter by Column"
    fds_filter_operator:  "Condition"
    fds_filter_rhs:       "Matching"
    fds_mutate_column:    "Column to Mutate"
    fds_mutate_rhs:       "New Value"
    fds_rename_column:    "Curret Column"   
    fds_rename_rhs:       "New Name"
    fds_group_column:     "Columns to Group"
  errors:
    fds_filter_column:    "Filter column not specified."
    fds_filter_operator:  "Filter codition not specified."
    fds_filter_rhs:       "Filter RHS not specified."
    fds_mutate_column:    "Mutate column not specified."
    fds_mutate_rhs:       "Mutate RHS not specified."
    fds_rename_column:    "Column to rename not specified."   
    fds_rename_rhs:       "New column name not specified."
    fds_group_column:     "No columns to group specified."
    unknown_action:       "The selection action is not supported."
    element_not_added:    "Unable to add the data wrangling element:"
  operators:  
    # Do not change the type or rop. Only modify the text element
    - type: "factor"
      text: "is one of"
      rop:  "%in%"
    - type: "factor"
      text: "is not"
      rop:  "!%in%"
    - type: "not_factor"
      text: "is within the range"
      rop:  "within"
    - type: "not_factor"
      text: "is equal to"
      rop:  "=="
    - type: "not_factor"
      text: "is not equal to"
      rop:  "!="
  # dimensions of the table preview in pixels
  actions:
    filter:
      choice:  "Filter"   
      subtext: "Filter data"
    mutate:
      choice:  "Alter"  
      subtext: "Change the contents of a column"
    rename:
      choice:  "Rename"  
      subtext: "Rename column"
    group:  
      choice:  "Group"   
      subtext: "Group subsequent operations by columns"
    ungroup:
      choice:  "Ungroup" 
      subtext: "Removing groping"                        
  preview:    
    width:  400
    height: 200
  code: # module specific code options
    readOnly: TRUE
    mode:     r    
